### ISSUE TITLE
Incorrect output on post

### ISSUE THREAD

**Issue by barranger** [sanfrancesco/create-react-app-blog#1]
After going through the tutorial on your blog, the blog index is working, however I'm getting the following output when clicking on the individual post:

![image](https://cloud.githubusercontent.com/assets/438877/23267396/a4352caa-f9b8-11e6-97d1-aaf3359f262f.png)

**Comment by jotto** [comment]
Thank you for filing the issue.

It looks like this broke as of version `0.8.0` of create-react-app, because since then they're using the `url-loader` as the default loader: https://github.com/facebookincubator/create-react-app/pull/1059/

Their default loader be overridden by prefixing a `!` to the beginning of the [dynamic require context](https://webpack.github.io/docs/using-loaders.html#usage):

**before**
```javascript
const webpackRequireContext = require.context('markdown-with-front-matter!./_posts', false, /\.md$/);

```

**after**
```javascript
const webpackRequireContext = require.context('!markdown-with-front-matter!./_posts', false, /\.md$/);

```

Thanks again - I've updated the blog post: https://www.prerender.cloud/blog/2016/10/20/create-react-app-blog
