### ISSUE TITLE
Does not work with react-router v4: 'react-router' does not contain an export named 'browserHistory'

### ISSUE THREAD

**Issue by kentoj** [sanfrancesco/create-react-app-blog#2]
For guide posted here: 
https://www.prerender.cloud/blog/2016/10/20/create-react-app-blog

I get an error after adding browserHistory: **'react-router' does not contain an export named 'browserHistory'.**

It looks like the router was rewritten from scratch in v4: https://github.com/ReactTraining/react-router/issues/5263

Any chance this guide will be updated?

**Comment by jotto** [comment]
I updated the blog post and the documentation in this guide to point out specific versions that work.

As of Dec, 2017: react-router@3.2, react-helmet@4.0 (later react-helmet versions work too, but I'm mentioning it to be safe).

I don't think upgrading to react-router v4 is too important (since react-router v3 works great) - but I'm open to any pull requests - or ideally, a change that supports react-router v3 and v4.

**Comment by scm-developer1** [comment]
react-router@3.2
